version: "3.1"


services:
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"


networks:
  botnet:
    driver: bridge


